require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
  TargetRailsVersion: 5.1
  DisplayCopNames: true
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/EmptyLineAfterGuardClause:
  Enabled: true
